a = input('Digite algo: ')
print(f'Tipo primitivo: {type(a)}')
print(f'É um número? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanúmerico? {a.isalnum()}')
print(f'Está em maiusculo? {a.isupper()}')
print(f'Está em minusculo? {a.islower()}')
print(f'Só tem espaços? {a.isspace()}')
print(f'Está capitalizado? {a.istitle()}')
